<?php

/**
 *@file
 *article.module
 *
 */
function opiniones_section_block_info(){
  // This example comes from node.module.
  $blocks['articles'] = array(
    'info' => t('Opiniones Section Module'),
  );

  return $blocks;
}

function opiniones_section_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'articles':
    Global $base_url;

    $opiniones = array();
    $opinionesTitles = array(3 => "norte", 4 => "centro", 5 => "sur", 6 => "poniente");
    // print_r("opinionesTitles: ");
    // print_r($opinionesTitles);
    for($i = 3; $i < 7; $i++){
      $item = $i+1;
      $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, B.entity_id, B.field_type_value FROM {node} A INNER JOIN {field_data_field_type} B ON A.nid = B.entity_id WHERE A.type = :type AND B.field_type_value = ".$item." ORDER BY nid DESC LIMIT 1";
      $opinion = db_query($query, array(':type' => 'articulo'))->fetchAll();

      if(!empty($opinion)){
        $a_id = $opinion[0]->nid;

        // Execute queries to get slide info: image, title (description).
        if (is_numeric($a_id)){

          // Get: Image.
          $image = db_query("SELECT entity_id, revision_id, field_image_profile_fid FROM {field_data_field_image_profile} WHERE entity_id = :eid", array(':eid' => $a_id))->fetchObject();

          $i_fid = $image->field_image_profile_fid;
          if (is_numeric($i_fid)){
            $image_profile_file = db_query("SELECT fid, uid, filename FROM {file_managed} WHERE fid = :fid", array(':fid' => $i_fid))->fetchObject();
            $image_file = $image_profile_file->filename;
          }
          else{
            $image_file = "gente.png"; //default image 
          }

          // Get: Title (description).
          $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, B.entity_id, B.field_title_value FROM {node} A INNER JOIN {field_data_field_title} B ON A.nid = B.entity_id WHERE B.entity_id = :e_id";

          $title_field = db_query($query, array(':e_id' => $a_id))->fetchObject();
          $title = $title_field->field_title_value;
        }
        else{
          $image_file = "gente.png"; //default image 
          $title = "No title"; //default title
        }        
      }
      else{
        $image_file = "gente.png";
        $title = "No title";
      }

      $image_url = '"'.$base_url.'/sites/default/files/'.$image_file.'"';
      $opinion[0]->image_name = $image_file;
      $opinion[0]->image_url  = $image_url; // str_replace(" ", "%20", $image_url);

      $opinion[0]->description = $title; 

      $opinion[0]->title = $opinionesTitles[$i];

      array_push($opiniones, $opinion);
    }

    // print_r('opiniones -> ');
    // print_r($opiniones);


    // Get current path
    $path = current_path();
    if($path == "node/6"){
      //opiniones_slider
      $section = "
      <div class='opiniones_section'>
        <div class='opiniones_title'> 
          <p> Opiniones </p>
        </div>
        <div class='opiniones_container'>";

      $fix_prof_image = '"'.'http://libertasmorelos.lo/sites/default/files/opinion_user.png'.'"';
      // Sección fija
      $section .= "
      <div class='opiniones_fix_container'>
        <a href='' class='opiniones_fix_link'>
          <div class='opiniones_fix_section'>
            <div class='opiniones_fix_image' style='background-image: url(".$fix_prof_image.");'> </div>
            <div class='opiniones_fix_info'>
              <p class='opiniones_fix_title'> Desde los Laureles por Teodoro Renter&iacute;a </p>
              <p class='opiniones_fix_description'> This is the description. Leer m&aacute;s... </p>
            </div>
          </div>
        </a>
        <a href='' class='opiniones_fix_link'>
          <div class='opiniones_fix_section'>
            <div class='opiniones_fix_image' style='background-image: url(".$fix_prof_image.");'> </div>
            <div class='opiniones_fix_info'>
              <p class='opiniones_fix_title'> La ley de Herodes por  </p>
              <p class='opiniones_fix_description'> This is the description. Leer m&aacute;s... </p>
            </div>
          </div>
        </a>
        <a href='' class='opiniones_fix_link'>
          <div class='opiniones_fix_section'>
            <div class='opiniones_fix_image' style='background-image: url(".$fix_prof_image.");'> </div>
            <div class='opiniones_fix_info'>
              <p class='opiniones_fix_title'> Contratiempo por </p>
              <p class='opiniones_fix_description'> This is the description. Leer m&aacute;s... </p>
            </div>
          </div>
        </a>
      </div>
      " ; 
      $section .= "<div class='opiniones_slider'>";

      foreach ($opiniones as $opinion) {
        // print_r("opinion");
        // print_r($opinion);
        // Link: Redirect to HOME if the article validation is empty.
        $section .= "          
          <div class='opiniones_slide'>
            <div class='opiniones_wrapper'>
              <a class='opiniones_link' href='http://libertasmorelos.lo/node/".$opinion[0]->nid."'>
                <div class='opiniones_content ".$opinion[0]->title."'>
                  <div class='opiniones_content_image' style='background-image: url(".$opinion[0]->image_url.");'> </div>
                  <div class='opiniones_content_info'>
                    <p class='opiniones_content_title'> ".$opinion[0]->title." </p>
                    <p class='opiniones_content_description'> ".$opinion[0]->description.". Leer m&aacute;s... </p>
                  </div>                
                </div>
              </a>
              <a class='opiniones_link' href='http://libertasmorelos.lo/node/".$opinion[0]->nid."'>
                <div class='opiniones_content ".$opinion[0]->title."'>
                  <div class='opiniones_content_image' style='background-image: url(".$opinion[0]->image_url.");'> </div>
                  <div class='opiniones_content_info'>
                    <p class='opiniones_content_title'> ".$opinion[0]->title." </p>
                    <p class='opiniones_content_description'> ".$opinion[0]->description.". Leer m&aacute;s... </p>
                  </div>         
                </div>
              </a>
            </div>
          </div>
          ";
      }

      $section .= "</div>";
      $section .= "
        </div>
      </div>";

      $block['subject'] = t(''); //This is opiniones Section Block
      $block['content'] = $section;
    }
      break;
  }
  return $block;
}
