<?php

/**
 *@file
 *article.module
 *
 */
function destacados_section_block_info(){
  // This example comes from node.module.
  $blocks['articles'] = array(
    'info' => t('Destacados Section Module'),
  );

  return $blocks;
}

function destacados_section_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'articles':
    Global $base_url;

    $destacados = array();
    $destacadosTitles = array(0 => "ejecutivo", 1 => "legislativo", 2 => "judicial");
    // print_r("destacadosTitles: ");
    // print_r($destacadosTitles);
    for($i = 0; $i < 3; $i++){
      $item = $i+1;
      $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, B.entity_id, B.field_type_value FROM {node} A INNER JOIN {field_data_field_type} B ON A.nid = B.entity_id WHERE A.type = :type AND B.field_type_value = ".$item." ORDER BY nid DESC LIMIT 1";
      $destacado = db_query($query, array(':type' => 'articulo'))->fetchAll();

      if(!empty($destacado)){
        $a_id = $destacado[0]->nid;

        // Execute queries to get slide info: image, title (description).
        if (is_numeric($a_id)){

          // Get: Image.
          $image = db_query("SELECT entity_id, revision_id, field_image_profile_fid FROM {field_data_field_image_profile} WHERE entity_id = :eid", array(':eid' => $a_id))->fetchObject();

          $i_fid = $image->field_image_profile_fid;
          if (is_numeric($i_fid)){
            $image_profile_file = db_query("SELECT fid, uid, filename FROM {file_managed} WHERE fid = :fid", array(':fid' => $i_fid))->fetchObject();
            $image_file = $image_profile_file->filename;
          }
          else{
            $image_file = "gente.png"; //default image 
          }

          // Get: Title (description).
          $query = "SELECT A.nid, A.vid, A.uid, A.type, A.status, B.entity_id, B.field_title_value FROM {node} A INNER JOIN {field_data_field_title} B ON A.nid = B.entity_id WHERE B.entity_id = :e_id";

          $title_field = db_query($query, array(':e_id' => $a_id))->fetchObject();
          $title = $title_field->field_title_value;
        }
        else{
          $image_file = "gente.png"; //default image 
          $title = "No title"; //default title
        }        
      }
      else{
        $image_file = "gente.png";
        $title = "No title";
      }

      $image_url = '"'.$base_url.'/sites/default/files/'.$image_file.'"';
      $destacado[0]->image_name = $image_file;
      $destacado[0]->image_url  = $image_url;

      $destacado[0]->description = $title; 

      $destacado[0]->title = $destacadosTitles[$i];

      array_push($destacados, $destacado);
    }

    // print_r('destacados -> ');
    // print_r($destacados);


    // Get current path
    $path = current_path();
    if($path == "node/6"){

      $section = "
      <div class='destacados_section'>
        <div class='destacados_title'> 
          <p> Destacados </p>
        </div>
        <div class='destacados_container'>";

      foreach ($destacados as $destacado) {
        // print_r("destacado");
        // print_r($destacado);
        // Link: Redirect to HOME if the article validation is empty.
        $section .= "
          <a href='http://libertasmorelos.lo/node/".$destacado[0]->nid."'>
          <div class='destacados_content ".$destacado[0]->title."'> 
            <p class='destacados_content_title'> ".$destacado[0]->title." </p>
            <div class='destacados_content_image' style='background-image: url(".$destacado[0]->image_url.");'> </div>
            <p class='destacados_content_description'> ".$destacado[0]->description." </p>
            <div class='destacados_content_separator'></div>
          </div>
          </a>";
      }

      $section .= "
        </div>
      </div>";

      $block['subject'] = t(''); //This is destacados Section Block
      $block['content'] = $section;
    }
      break;
  }
  return $block;
}
